### ISSUE TITLE
2 spaces + newline for new line 

### ISSUE THREAD

**Issue by karasjoh000** [notable/notable#1117]
- **OS Version**:
macOS mojave
- **Notable Version**:
newest one

needs new line for 2 spaces followed by carraige return/newline. However no newlines are made.

**Comment by fabiospampinato** [comment]
I don't understand what the issue is, can you post the Markdown that causes the problem?

**Comment by bluebirch** [comment]
I guess it refers to other flavours of markdown, such as [pandoc's markdown](https://pandoc.org/MANUAL.html#pandocs-markdown):

> A paragraph is one or more lines of text followed by one or more blank lines. Newlines are treated as spaces, so you can reflow your paragraphs as you like. If you need a hard line break, put two or more spaces at the end of a line.

In pandoc and similar markdown flavours,

```markdown
this
too
```

becomes

> this too

To force a hard line break, add two spaces:

```markdown
this␣␣
too
```

Notable markdown doesn't support that. It would actually be nice if it did, since I use pandoc extensively to render markdown files into PDF. (There is an issue with titles and metadata with pandoc too, maybe I should file a separate issue?)

**Comment by fabiospampinato** [comment]
> I guess it refers to other flavours of markdown, such as pandoc's markdown:

I see. That's now how the most common implementations of Markdown work. I don't think this will be implemented in Notable as this conflicts with the option for trimming trailing whitespaces many popular editors have, I don't think it's wise to basically encode information in trailing (non-newline) whitespaces.

> There is an issue with titles and metadata with pandoc too, maybe I should file a separate issue?

Yes please.
