### ISSUE TITLE
I sponsored you, how do I get access to the chat?

### ISSUE THREAD

**Issue by ramonza** [notable/notable#1121]

**Comment by ramonza** [comment]
Please reach out to me on Signal or WhatsApp +14152386373

**Comment by fabiospampinato** [comment]
Hello there, where did you sponsor me, on GitHub? I don't see you as a sponsor right now.

There were a handful of sponsors I couldn't get the email of from their github profile via [github-email](https://github.com/paulirish/github-email), and I can't get your email with that so that's probably why I haven't sent you the invitation yet. GitHub allows me to contact all sponsors at once basically, but not on a 1-by-1 basis, and I didn't want to just send 30 identical emails to my earliest sponsors, so I was planning to send a one-off email for the v1.9 release.

Could you send me an email at fabio@notable.md?

**Comment by fabiospampinato** [comment]
Hey @ramonza, thank you very much for your donation! Do you mind sending me an email at fabio@notable.md so that I can send you the invitation link to the chat?
