### ISSUE TITLE
iCloud Notes Backend

### ISSUE THREAD

**Issue by ramonza** [notable/notable#1130]
### Feature description

Use iCloud Notes as a backend. 

### Feature motivation

I use Apple Notes. It has an iPhone app. I can't switch to a notes tool without an iPhone app and I'm pretty sure most of my fellow Apple Notes users would feel the same.

Instead of building a new iPhone app, why not just use the data stored in iCloud in Apple Notes. There's an API for it (not official): https://github.com/MauriceConrad/iCloud-API

Probably not too hard to reverse-engineer the note format. The iCloud syncing backend is actually quit good (I'm biased, I used to work on it :). The sharing feature is very nice but the UI for it could use some work.

PS: I don't work at Apple anymore so don't worry about a conflict of interest

**Comment by fabiospampinato** [comment]
I have no intention to offer a different front-end for Apple Notes, that doesn't align with my goals with the app. 

As far as the cloud goes I don't think iCloud was build for use cases like mine in mind, we need something more like AWS.

Until the official mobile app is here, which will be more like a port of the current one than a new one written from scratch, I've heard some people on iOS are accessing their notes via Ai Writer or similar programs. It isn't perfect, but if you mostly manage your notes from the computer it should be usable.

**Comment by ramonza** [comment]
Would you accept a pull request if I wrote this myself as an option that the user could enable?

**Comment by fabiospampinato** [comment]
🤔 it's a tricky question, there are many ways to think about this.

Generally I would say kind of the final goal here is to make something amazing, something much better than anything else, that provides a lot of value to users. In order to do that many man-years must be put into developing the app, and in order to do that those man-years must be paid for, i.e. the app as a whole must become financially sustainable.

In order to become sustainable the route that I'm taking is eventually asking for a subscription fee for accessing the official mobile app and related services, this may change in the future, like maybe the app could become completely free for individuals but paid for teams or something, but for now that seems like the best route to me.

So what effects would adding an integration with Apple Notes have on this? 

I think mostly only positive effects: if one wants to use Notable with Apple Notes he/she could, making the app better for him/her, on the other hand this could make paying for accessing the official mobile app less appealing, making the project harder to sustain, but I think that will be an incentive toward making the app better until eventually people would want to switch, so this may actually be a positive effect too.

The major negative effect that I can see right now is that adding integration with Apple Notes now, even if you submit a PR for it, which would be about a pretty core feature which would not be easy to integrate with the app (at this point the open-source version of the app works pretty differently than my development branch in this regard), would still require significant time effort on my end too, possibly both for merging the PR and maintaining this feature, effort that I would rather put toward developing the official mobile app instead.

I can see a path for integrating this with the app though, I don't know if this would work for you but I think it should be a quite reasonable middle ground:

1. You could develop this outside of Notable itself. Since Notable has kind of an open database, i.e. it synchronizes everything with the filesystem, you could make an external tool that pushes changes happening in the filesystem to iCloud, and changes happening in iCloud to the filesystem, the app would just notice those changes happening in the filesystem and update accordingly. I think this would allow you to have pretty much exactly what you want, without me having to spend any effort on this.

2. Once the app matures there's a path for turning this external tool into a plugin, I plan to develop a plugins ecosystem at some point #128, and our backends could be pluggable too potentially, allowing a plugin to be made out of this hypothetical external iCloud synchronization tool that at that point in time could be integrated with the app still without me needing to maintain it, and while allowing for other backends too, I'd only need to maintain the related plugin APIs.

There's also the possibility that once the official mobile app gets released you would want to use that instead, and the effort required to write the iCloud synchronization tool or the future related plugin APIs won't even be needed anymore.

Does that sound reasonable?

**Comment by ramonza** [comment]
yeah that totally makes sense. I wasn't aware of the long-term goals around the project so I was more offering this as a way to avoid writing and maintaining a server-side project entirely.
