### ISSUE TITLE
Notes in trash interfere with naming and make linking harder

### ISSUE THREAD

**Issue by luism6n** [notable/notable#1158]
- **OS Version**: MacOS High Sierra 10.13.6
- **Notable Version**: 1.8.4

### Current behavior

- Create note titled "foo" (foo.md is created in the notable dir)
- Move "foo" to the trash
- Create another note titled "foo" (foo (2).md is created)
- Try to link to newly created note with `[@notes/foo]`
- Link points to trash note
- To link to the right note, you must use `[@notes/foo (2)]`, even though "(2)" is not shown in the UI.

Also, if I delete an untitled noted, all my new notes appear as "Untitled (2)".

### Expected behavior

Note title is always the name used to link.

**Comment by fabiospampinato** [comment]
What you want are reliable links, let's track this there: https://github.com/notable/notable/issues/1159

> Also, if I delete an untitled noted, all my new notes appear as "Untitled (2)".

There's a bit of a delay before a previously used file name becomes available.

> Note title is always the name used to link.

That's not really a solution though, if there are 2 titles with the same name, which fundamentally is the issue here, which one of them should the link point to? It may happen also that you link to "Foo", then rename "Foo" to "Bar", then create a new note titled "Foo", now previous links pointing to "Foo" are pointing to a different note, that shouldn't happen.
