### ISSUE TITLE
Wrong filename with `(2)` at the end

### ISSUE THREAD

**Issue by lastingman** [notable/notable#1178]
- **OS Version**: macOS Catalina 10.15.5
- **Notable Version**: 1.8.4

### Current behavior

The filename is different from the title in Notable.

![image](https://user-images.githubusercontent.com/10057502/83830926-e5856600-a718-11ea-9e1f-ec5ca33f69bf.png)

There is `(2)` at the end of the filename.

### Expected behavior

The filename should be the same as the title in Notable.

**Comment by fabiospampinato** [comment]
> The filename should be the same as the title in Notable.

This is impossible in general, as you can have two notes with the same title but not two files in the same folder with the same name.

You are seeing that "(2)" being added because previously there was a note without that there, and it wasn't safe to reuse the same filename. The situation on this matter improved a bit in v1.9, but fundamentally we can't really avoid using these kind of file names.
