### ISSUE TITLE
Non-destructive metadata updates

### ISSUE THREAD

**Issue by col** [notable/notable#1192]
### Feature description

You're currently storing your metadata, such as `title`, `tags`, `created` etc using what looks like the `Yaml Front Matter` method which is also used by several other tools most importantly Jekyll. (Reference: https://jekyllrb.com/docs/front-matter/) 

Unfortunately, Notable currently re-writes the metadata section whenever there's an update which removes any additional metadata key/values that may have been added to the doc.

If you could make the metadata changes non-destructive so that any unknown keys are not removed it would open up a whole lot of possibilities for alternative workflows.

### Feature motivation

It would be really awesome to be able to edit Jekyll content from Notable. I realise Jekyll content editing is probably not the primary target of Notable but I'm hoping this is a relatively small change that would allow it. Jekyll is also pretty widely used so this feature could open Notable up to a wider audience.

**Comment by beet** [comment]
Similarly, I tried moving the metadata somewhere else in the page, and when saving it was forced back to the top.

This causes issues for other Markdown apps that don't work with metadata and expect notes to follow the convention of beginning with a Markdown heading.

The option to append the metadata to the end of the note, instead of forcibly prepending it to the beginning, would open up a lot of opportunities for using Notable as a companion to other note taking apps _(or visa versa, depending on your perspective 😀)_

**Comment by fabiospampinato** [comment]
@beet Moving the metadata section to the bottom is just a ugly workaround, the proper fix is using apps that support the frontmatter section rather.

**Comment by beet** [comment]
Sure, it is called _front_ matter after all. I have a lot of apps and tools for working with Markdown, but frontmatter support isn't that widespread yet. The option to edit files in Notable _without_ saving frontmatter to them would open it up to working with them, but as it is, I can't save a file in Notable that I intend to work with in another app, which is a shame, because Notable really is one of the best that I've come across so far.

In fact, if I was starting a new knowledge-base from scratch, it would be pretty close to perfect for me as-is, it's a great app.

**Comment by fabiospampinato** [comment]
@beet Hopefully eventually those other apps will start supporting the frontmatter section and/or Notable would just replace them.

**Comment by col** [comment]
This has been implemented in one of the alpha releases. Not sure exactly when it was introduced but I have verified it in both `1.9.alpha.19` and `1.9.alpha.20`.
