### ISSUE TITLE
Notable security

### ISSUE THREAD

**Issue by nickbe** [notable/notable#1335]
How can we prevent notable from sending requests to any server except our own? Or in other words: Is it possible to share and store notes on our own server?

**Comment by fabiospampinato** [comment]
> How can we prevent notable from sending requests to any server except our own?

Turn the router off, or firewall the app off the internet, or patch the last open-source version of the app to not use the internet at all.

> Or in other words: 

That's another question really.

> Is it possible to share and store notes on our own server?

In some sense yes, meaning that you have full access to your notes of course, and you can do whatever you want with them. Self-hosting the sharing service running at `echo.notable.app` is not possible because that's not open-source but you might reimplement that and maybe even redirect requests to that domain to some other domain at the OS level or something, I'm not sure if that's possible. Eventually plugins will be able to reimplement search in other ways if they so desire.

**Comment by nickbe** [comment]
So basically what you're saying is that except by patching the source code, there's no configuration option to turn of sharing the notes with your server?

**Comment by fabiospampinato** [comment]
I mean you can remove the button completely from the custom CSS/JS editor in v1.9, other than that sharing is opt-in, don't use it if you don't want it.
