### ISSUE TITLE
Custom data directory per root tag

### ISSUE THREAD

**Issue by bediu** [notable/notable#1357]
### Feature description
A custom data directory specific to a root tag.

### Feature motivation
I want to manage multiple projects using nested tags, but some projects I want to share with other users via github, some I want to keep them private. Custom data directories per root tag would allow such feature. 

Alternatively, introduce a "Projects" feature that by functionality is just a root "tag" with custom properties, such as it's own working directory, icon, maybe even color etc.

**Comment by fabiospampinato** [comment]
Each notebook in the future will have it's own folder on disk, I think this should suffice for your use case. #54 

Alternatively you can also export all notes in a tag at once and share that exported folder with other users.

Lastly one window may be able in the future to manage multiple data directories at once, let's track this here: https://github.com/notable/notable/issues/60

Tags can't be associated with folders because notes can be assigned to multiple tags but can't be assigned to multiple folders.
