### ISSUE TITLE
Publish to Chocolatey

### ISSUE THREAD

**Issue by salecharohit** [notable/notable#145]
No chocolatey package found for auto-installation on Windows.

**Comment by salecharohit** [comment]
Thanks for prompt reply. 
https://chocolatey.org/docs/create-packages

**Comment by fabiospampinato** [comment]
Let's keep this issue open until it's actually published there.

**Comment by bspeice** [comment]
I'm actually planning to take a look at this, I maintain some other packages and it's not hard to add another. Couple questions if you don't mind:

1. Do you want to own the package/repository, and I just get it set up? If you have access to a Windows machine, it's just two commands to build and publish a new release. Alternately, I can integrate it into the things I already manage (and give you commit access).

2. Should the "Setup" or regular "exe" version be distributed?

Just started using the application, and I'm looking forward to making use of it for a while to come.

**Comment by salecharohit** [comment]
Well i am more of a chocolatey user , without any experience in programming the kind of stuff you are building :-P
However i can always test the solution for you.
Not sure if you require Setup or regular exe probably chocolatey documentation may help. I have never really uploaded any package there.

**Comment by fabiospampinato** [comment]
@bspeice:

> Do you want to own the package/repository, and I just get it set up?

I think it would be better if I owned the package. I have access to a Windows VM, that should be enough I guess.

> Should the "Setup" or regular "exe" version be distributed?

I'm not sure, as a Windows user which one do you think would make more sense to use?

**Comment by bspeice** [comment]
VM is totally fine, but will need [au](https://github.com/majkinetor/au) installed. The standard is to install the Setup version so that you get start menu, etc. 

I'm going to get a package up and running inside my repository just to start with, and I'll be happy to transfer ownership (and the packaging code) once I confirm that everything's good to go! Right now I'm having issues parsing Github's download page, Powershell isn't playing nice.

**Comment by fabiospampinato** [comment]
@bspeice thank you!

**Comment by bspeice** [comment]
@fabiospampinato - Are you available on Gitter/etc. that I can follow up with further maintenance info? I don't know if it's relevant to the Github issue.

**Comment by fabiospampinato** [comment]
@bspeice you can ping me directly at spampinabio@gmail.com

**Comment by bspeice** [comment]
Version 1.0.1 was approved and is now available!

The wrong icon is currently displayed, but that's fixed as of the 1.1.0 version. That will likely be approved shortly, but the chocolatey install is good to go as far as I'm aware. I think this request is complete?

**Comment by fabiospampinato** [comment]
I'll keep the issue open to keep track of this until I can maintain the package myself.

**Comment by salecharohit** [comment]
choco install notable ! awesome !

**Comment by bspeice** [comment]
I've been holding off on pushing the recent release to give @fabiospampinato a chance to do it if you'd so prefer. Otherwise, I'm planning on sending up the chocolatey package this evening EST so that everything's kept up to date.

**Comment by fabiospampinato** [comment]
@bspeice I haven't had the time to set this things up properly yet, there are still some more pressing issues that I prefer to work on.

**Comment by bspeice** [comment]
Good call. I'll go ahead and keep Chocolatey in sync for now, let me know when you're ready to take this over.

**Comment by fabiospampinato** [comment]
I'm closing this because @bspeice has done a wonderful job at publishing the app to Chocolatey and keeping it up up-to-date: https://chocolatey.org/packages/notable

Run the following to install it:

```bash
choco install notable
```

At some point I'd like to manage this myself, but as the app is actually already published to Chocolatey, and I'm confident the Chocolatey package will be managed well there, I'm closing this issue.
