### ISSUE TITLE
Color highlighting is not consistent

### ISSUE THREAD

**Issue by fabiosirna** [notable/notable#167]
Hi @fabiospampinato 
here another bug:

https://www.dropbox.com/s/thgtjmr25f9g9qx/Screenshot%202019-01-02%2017.23.09.png?dl=0
https://www.dropbox.com/s/5kw9ificr110bw1/Screenshot%202019-01-02%2017.27.07.png?dl=0

as you can see from the screenshot the color highlighting is not always consistent. I'm not sure if it's a Notable bug or related to CodeMirror.

**Comment by fabiosirna** [comment]
I did a test with the same code provided as a sample from [CodeMirror](https://codemirror.net/mode/shell/index.html)

https://www.dropbox.com/s/jj6pj0lyptz6982/Screenshot%202019-01-02%2017.29.47.png?dl=0

as you can see, color a part, the color highlighting is broken.

**Comment by RomanKornev** [comment]
You can specify a language via
```
    ```bash
    YOUR CODE HERE
    ```
```
Works as expected
```bash
grep -Eorh 'http|https)://[^/"]+' * | sort | uniq
```

```bash
find /dir -name "*.jpg" -exec mv {} dirnew/  \;
```

Unless you're talking about difference between Edit mode (CodeMirror) vs Preview mode (hl.js)?

**Comment by fabiosirna** [comment]
Thanks @RomanKornev 

Specifying the language it works. Didn't know about it. I thought it was recognising the language automatically :)

**Comment by fabiosirna** [comment]
@RomanKornev @fabiospampinato 

As another sample, I'm providing here another issue. I was taking a note about a software license I have and here the result:

https://www.dropbox.com/s/vqj7amjfzku7k0c/Screenshot%202019-01-03%2011.08.04.png?dl=0

and this is the code (with a fake license, but same schema):

```
    # My Note

    ## Personal License

    ```
    A1-FAKE-123x56x8912x4b678912x456789d2345
    ```
```

**Comment by fabiospampinato** [comment]
> As another sample, I'm providing here another issue. I was taking a note about a software license I have and here the result:

Unless it gets rendered the same way as GitHub renders it, which doesn't seem the case to me, I would consider this a bug.

**Comment by HaleemDream** [comment]
@fabiospampinato 

Seems like the markdown syntax highlighting does not work?

In edit mode:
https://imgur.com/y4awqK9

In view mode:
https://imgur.com/Q4vWN83

How it should look (From GitHub):
https://imgur.com/a/fMzZGld

**Comment by fabiospampinato** [comment]
@HaleemDream yeah the highlight between edit and view mode is not the same and it's not the same one GH applies.

**Comment by fabiospampinato** [comment]
Currently the highlighting performed by the editor ([Monaco](https://github.com/Microsoft/monaco-editor)) and the preview syntax highlighter ([Prism](https://github.com/PrismJS/prism)) is not 100% consistent, both to themselves and to GitHub's. 

In order to make the highlighting between edit and preview more consistent I guess we might have to render an editor for each codeblock. This causes some performance problems and will also be problematic with exporting. But will also help in some scenarios (#493).

In order to make the highlighting between preview and GitHub more consistent I guess we would have to use GitHub's highlighter. Maybe backtracking here a little bit I don't think that closing this (small) gap is super important though.

**Comment by fabiospampinato** [comment]
Closing in favor of https://github.com/notable/notable/issues/719
