### ISSUE TITLE
Edit mode Ctrl+Click vs Alt+Click inconsistent behaviour

### ISSUE THREAD

**Issue by RomanKornev** [notable/notable#254]
- **OS Version**: Windows 10 x64 1809
- **Notable Version**: master 0eee7e273ec9f7288590c623f44884670ede44e8

### Current behavior
1. <kbd>Ctrl+Click</kbd> anywhere on the screen in Edit mode and cursor disappears. Typing is disabled even if text is selected.
2. <kbd>Ctrl+DoubleClick</kbd> keeps the previous cursor and selects highlighted word as well resulting in multiple cursors.
3. <kbd>Alt+Click</kbd> is used for generating multiple cursors as well.
4. But <kbd>Alt+DoubleClick</kbd> doesn't select highlighted word. It just resets all cursors to the current mouse position.
3. <kbd>Alt+Click</kbd> also doesn't allow dragging selection zone.

### Expected behavior
* <kbd>Ctrl+Click</kbd> is used anywhere to generate multiple cursors, preserving already existing selection.
* <kbd>Ctrl+DoubleClick</kbd> adds the currently highlighted word to selection and generates a cursor as well.
* <kbd>Ctrl+Click+Drag</kbd> adds a draggable selection zone to current selection and generates a cursor as well.
* <kbd>Alt+Click</kbd> is just used to select a zone. Not add or subtract.
* <kbd>Alt+DoubleClick</kbd> - select highlighted word. Reset selection if exists.
* <kbd>Alt+Click+Drag</kbd> - just a regular select. If selection starts in already existing selection zone - reset it unlike regular <kbd>Click+Drag</kbd> (which moves actual content of selection into a new place).

Not sure if replacing CodeMirror with Monaco #203 will fix it or not.

**Comment by fabiospampinato** [comment]
I think most of this will be fixed once we switch to Monaco #203 and once the editor is customizable.

**Comment by fabiospampinato** [comment]
Since this issue was first opened we switched to Monaco, so a few things changed. I've just checked that Alt+Click/DoubleClick/Drag works on all systems and:

- macOS: it works.
- Windows: it works.
- Linux: it conflicts with OS-level shortcuts, so now we are going to use Ctrl+Click/DoubleClick/Drag instead.

How multi-cursors per se work seem very aligned with how they work in VSCode now, since we are using the exact same editor under the hood, so I'd say we've got no problem there.

The last bit of feedback in this issue is being able to also use Ctrl+Click on macOS and Windows:

- macOS: that's used for triggering a right click.
- Windows: sounds like a good idea, but the editor doesn't allow us to use 2 different modifier keys with multi-cursors at the same time. I'd be happy to enable support for that once the editor itself adds support for it.
