### ISSUE TITLE
Show version-specific changelog/tutorial/license

### ISSUE THREAD

**Issue by amelandri** [notable/notable#378]
Today I opened the changelog from the app Help menu (v 1.2) and saw the release notes for 1.3, even if it's not released.

For an end-user point of view it would be better to have a development branch.

**Comment by fabiospampinato** [comment]
I see the problem, but the development branch is the "master" branch basically.

The problem here is that if you're using v1.1 you should only see the changelog/tutorial/license etc. for v1.1. Ideally you should also be able to see all those if you're offline. I'll work on that 👍

**Comment by fabiospampinato** [comment]
I'm closing this because now:

- The link to the online tutorial doesn't point to the current version but to the version of the tutorial that shipped with the version of the app that you're running.
- The version-specific, offline-capable, changelog is displayed inside the app, screenshot below.

<img width="685" alt="Screen Shot 2019-07-25 at 16 04 30" src="https://user-images.githubusercontent.com/1812093/61880972-26580000-aef6-11e9-88b0-59fe09bf8fc0.png">
