### ISSUE TITLE
PlantUML support

### ISSUE THREAD

**Issue by 181502** [notable/notable#379]
### Feature description

Just as mermaid is supported, I would like to see plantuml diagrams(plantuml.com) supported as well

### Feature motivation

Would make it possible to add uml digrams to noites

**Comment by kulkarniamit** [comment]
+1 for plantuml support.

**Comment by fabiospampinato** [comment]
@kulkarniamit Just add your "👍" to the main post, "+1" comments just waste people's time.

I've taken a closer look at this and it seems that PlantUML is a Java application, and JS plugins that enable support for it, like [this](https://github.com/gmunguia/markdown-it-plantuml/blob/master/index.js) work pretty weirdly, basically encoding diagrams in a url that plantuml.com will then render.

On one hand this adds almost nothing to the codebase, on the other end who wants to wait for networks roundtrips, have this not work when offline, and having their diagrams transparently sent to a server somewhere? 🤔 

I there was a WASM or pure-JS version of PlantUML this could be implemented a lot better I think 🤔

**Comment by fabiospampinato** [comment]
Reference Docker configuration, in case we decide to set-up our own PlantUML server: https://docs.gitlab.com/ee/administration/integration/plantuml.html#docker

**Comment by davidmichaelhuber** [comment]
In case this feature goes live I personally would really appreciate if there is some kind of mechanism that ensures that every user knows about that external rendering is applied to one's notes. For example that one has to explicitly opt-in for PlantUML external rendering in the settings.

**Comment by fabiospampinato** [comment]
@davidmichaelhuber IMHO the ideal scenario is:

- Somebody comes up with a WASM PlantUML implementation that I can embed in the app and render everything locally.

As that's unluckily to happen I'd argue the next best thing is:

- I'll host the PlantUML renderer under `https://plantuml.notable.md`, so that no data is sent anywhere I don't control.
- PlantUML diagrams are rendered by default using that endpoint.
- Options are added for disabling PlantUML rendering and/or providing an alternative endpoint, so that the renderer could be self-hosted.

I'd rather not disable this by default for the following reasons:

- As far as I can see there really are no embeddable alternative renderers, so people who are using PlantUML ([vscode extension](https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml), [markdown-it plugin](https://www.npmjs.com/package/markdown-it-plantuml) etc.) are already having their diagrams sent somewhere.
	- This is IMHO less of a problem with my proposed implementation as I will be controlling the endpoint.
- Burying this feature under a setting switch will most probably mean that some people that will like this feature will never discover it and those who discover it will be bothered by this extra step they'll have to take to have the feature working.
	- And realistically how many people who'd like this feature and know about the setting switch will not enable it? I think it would make more sense to make this opt-out rather.

Just my 2c, if any PlantUML users would like to share their thoughts I'd be interested in earing those.

**Comment by davidmichaelhuber** [comment]
Factoring in the points you stated another opt-in strategy could be to capture ` ```plantuml` blocks and show some sort of a little warning icon next to them. Expanding the icon then can show a description that states that external rendering is needed for `PlantUML` as well as a button to enable that feature.

I personally just like it much more having to opt-in instead of having to opt-out for features that affect an applications local boundaries.

**Comment by fabiospampinato** [comment]
@davidmichaelhuber That sounds like a potentially good idea 🤔 Maybe that's the best option, however how many users that will have that icon/button/link shown to them would not click it? I can't imagine that would be anybody but a few maybe.

**Comment by davidmichaelhuber** [comment]
I would argue that a yellow or maybe even a high contrast (to the background) icon might be pretty noticeable inside of the markdown editor pane where one would only expect plain text. Also another indicator for the user will be the fact that their `PlantUML` didn't actually render. So the same warning icon might make sense in the rendered view.

The same opt-in mechanism then could also be used for external renderers that might be requested in the future.

**Comment by fabiospampinato** [comment]
Done.

I'll post a preview in the subreddit about this.

![image](https://user-images.githubusercontent.com/1812093/77203755-1f1add80-6ae9-11ea-8f7c-efdfe5154b21.png)

I haven't added a confirmation dialog as I don't think that would be very useful, I'm however hosting the renderer myself for added privacy: http://plantuml.notable.md

I'll add an option for supplying a custom renderer url, which other than enhancing privacy would make this work faster if the renderer is hosted locally.

**Comment by 0xsajjad** [comment]
Any hopes about this feature will be available anytime soon. No release after 20 Jan 2020, is this project dead?

**Comment by fabiospampinato** [comment]
> Any hopes about this feature will be available anytime soon. No release after 20 Jan 2020, rendering isn't working for the insider version.

The plantuml server is a big finicky at times, I haven't narrowed down why, you can try changing the endpoint from the setting to the official one, which I believe is either `https://www.plantuml.com/plantuml` or `https://www.plantuml.com`. If that doesn't work after a restart please open a separate issue as that's a bug.
