### ISSUE TITLE
File deleted 

### ISSUE THREAD

**Issue by edferoci** [notable/notable#399]
- **OS Version**: Win 10
- **Notable Version**: 1.2 and 1.3

### Current behavior

1. Set the Data Dir to a folder that is synched with Google Stream (Ver. 29.1.65.2046)
2. Insert some notes
3. Restart the app
A random note is deleted during the startup. The corresponding md file is no longer present 

### Expected behavior

Notes should be persistent

**Comment by fabiospampinato** [comment]
@edferoci That's Google Stream?

**Comment by edferoci** [comment]
sorry, I'm referring to Google Drive File Stream (https://www.google.com/drive/download/)

**Comment by fabiospampinato** [comment]
@edferoci I'll look into that 👍

**Comment by fabiospampinato** [comment]
@edferoci I'd start by checking which filesystem events are reported [here](https://github.com/fabiospampinato/notable/blob/master/src%2Frenderer%2Futils%2Fwatcher.ts/#L84).

**Comment by jarivo** [comment]
@fabiospampinato I've experienced the same behaviour as described by @edferoci.

I think this issue was introduced in version 1.2.0 and happens when you use e.g. WebDAV (probably used by Google Drive File Stream) or [Dokany](https://github.com/dokan-dev/dokany/).

So basically when you open Notable with the data directory pointed to a WebDav mounted "drive", random notes are deleted. If you then restart Notable, another x amount of notes are removed. I could repeat this process until I had 1 note left.

I already went through the code and looked at the diff between 1.2.0 & 1.1.0 (1.3.0 still has this issue). The watcher looks like the only relevant change that could cause this issue.

I'll play around with the watcher.ts implementation in a simple setup and see if I can reproduce this issue.

**Comment by jarivo** [comment]
@fabiospampinato 
It looks like the root cause is the ino value from fs.stat which is used for the renaming logic.
While using Dokany, for every file the ino value is currently always 0. (I don't think it has anything to do with https://github.com/nodejs/node/issues/12115).

In version v1.1.0 this wasn't a problem because the rename logic was only triggered by an unlink event.
With the refactoring of the renaming logic in v1.2.0 the inode value is now compared on every event.

This explains the behaviour @edferoci has with GDFS. The watcher waits 150 ms to check for other events. When you open Notable all the files trigger an add event. Due to the same inode values, rename events are emitted. Which causes some files to be removed.

Solving this won't be easy. Ignoring files with inode 0 will probably cause weird behaviour in Notable (I wasn't able to actually test this).

Thoughts?

**Comment by fabiospampinato** [comment]
@jarivo thanks a lot for looking into this! If I'm understanding this correctly basically right now 2 consecutive "add" events get interpreted as a "rename" event, I think we should: 

1. as a quick workaround first only listen for an "unlink" event after an "add" event (and vice versa).

2. long-term switch to something more reliable, like [`@atom/watcher`](https://github.com/atom/watcher/issues/204), but I couldn't get it work yet.

**Comment by fabiospampinato** [comment]
I believe I've just fixed this specific problem with https://github.com/notable/notable/commit/bbe0183af70f5cc447d45cb1e2240350985d9a03. Let me know in case you can still reproduce.

Still I don't think we are able to detect renames under these circumstances, I'm not sure how other libraries can do that either 🤔 

If anybody has any idea how to uniquely identify files in some other way than the ino number I'd be happy to hear that.

**Comment by jarivo** [comment]
@fabiospampinato bbe0183 does the trick. But it's indeed not possible the detect renames in that case.

> If I'm understanding this correctly basically right now 2 consecutive "add" events get interpreted as a "rename" event

That's correct.

> 2\. long-term switch to something more reliable, like [`@atom/watcher`](https://github.com/atom/watcher/issues/204), but I couldn't get it work yet.

I agree. It's probably better to delegate this responsibility to a dedicated module instead of handling all these quirks in Notable itself.

> If anybody has any idea how to uniquely identify files in some other way than the ino number I'd be happy to hear that.

I don't think there is anything else provided by Node itself.

**Comment by paperbound** [comment]
I'm still seeing this in MacOS 10.14.3 (18D109) with Notable 1.4.0 where my Data Directory is linked to iCloud Drive.

**Comment by fabiospampinato** [comment]
@paperbound Can you describe precisely the problem you're experiencing and how you can reproduce it?
