### ISSUE TITLE
Note duplicated itself after title changed

### ISSUE THREAD

**Issue by Soksovandavid** [notable/notable#420]
- **Windows 10**:
- **1.3.0**:

### Current behavior

So basically first of all I created a new note with the title 'Picture Frame' but then I realized the grammar is incorrect so I made a change on the title into 'Picture Frames' but instead of saving the changed within my current note, it created another one with that changed and left my main note unchanged. And the more note I changed, the more note it'll create. As you can see in the picture I made a title change 4 times just to see what happened and it created a new one every time.

![img](https://user-images.githubusercontent.com/31823046/52293117-b20dbc80-29a8-11e9-814d-df60f2fe3ebd.png)

**Comment by synapse** [comment]
I'm experiencing the same behaviour when adding a new note while the tag popup is open

**Comment by fabiospampinato** [comment]
I can reproduce this very easily if I trigger an autosave every 1ms while editing, my guess would be that if you are editing a note that is being autosaved this issue might happen some times, so having a longer autosave interval won't actually permanently fix this but only reduce it's chance of happening (I think the default interval as of v1.3 is 5s, maybe that's why not too many people have reported this issue).

I'm working on this right now 👍

**Comment by fabiospampinato** [comment]
I've removed the autosaving every X seconds feature https://github.com/notable/notable/commit/7e8406322adbec5019b084cab24a032ba0c20057 , as that was mostly useless (the editor gets saved automatically when leaving it and when focusing to something else, and that's good enough) and as a result I can no longer reproduce this.

Let me know if this bug resurfaces on v1.4.
