### ISSUE TITLE
A “Copy to clipboard” button on code blocks

### ISSUE THREAD

**Issue by Elarcis** [notable/notable#436]
### Feature description
Next to code blocks (opened via ```), a button allows to copy the content of that block to the clipboard.

### Feature motivation

I recently heard of [Code Notes](https://lauthieb.github.io/code-notes/), which provides snippet management, but I prefer the versatility of Notable. Only major advantage Code Notes has over Notable imho is a small button to quickly copy a snippet to the clipboard.

**Comment by fabiospampinato** [comment]
Just implemented, check [this](https://imgur.com/wrYbLoo). There's no notification when the copy to the clipboard has happened though, I also kind of expect one as a user but it's entirely useless, so let's try not having one, if you click the button the code gets copied, otherwise it doesn't get copied.
