### ISSUE TITLE
Note is deleted on slow drives

### ISSUE THREAD

**Issue by mikaelmello** [notable/notable#464]
- **OS Version**: Ubuntu 16.04 LTS (KDE)
- **Notable Version**: 1.3.0

### Current behavior

I am editing my notes on a directory that is always synced on any change, therefore the changes might take a while to propagate.

Since Notable apparently deletes the file and creates a new one when updating its title (I can clearly see the file vanishing and reappearing with a new name), when I close the Notable using Ctrl+W after a title change, the file is deleted but never recreated, everything is lost.

I've never looked into the code but I guess the update process is asynchronous to the one that exits the application, and then the application closes without waiting for the auto-save to finish, would that be correct?

### Expected behavior

If the new title is not updated, I should have at least the old note stored, not lose it.

**Comment by fabiospampinato** [comment]
Yes I think you're right. 

In order to fix this, and possibly other problems, I think we should just [rename](https://nodejs.org/api/fs.html#fs_fs_rename_oldpath_newpath_callback) the file rather than deleting and re-creating it, and we should also wait for any pending storage activities and API calls.

**Comment by mikaelmello** [comment]
I tried to reproduce by changing anything inside the note, but not the title and the behavior seems to remain the same.

The note was still there but was completely empty, I guess that I just happened to close Notable right after creating the file.

**Comment by fabiospampinato** [comment]
> I tried to reproduce by changing anything inside the note, but not the title and the behavior seems to remain the same.

I think we are only deleting the note if the title/inferred filepath changes. 🤔 

To give some more context: earlier in its development we were waiting for changes on disk before updating the UI, that meant that if you favorited a note there would be a noticeable delay between you clicking the button and the UI updating accordingly. As a performance optimization before releasing the app I used a technique called "optimistic rendering", basically now we are updating the UI immediately, assuming that the storage will be updated properly. Long story short the function that's deleting the note was rightfully doing so considering the previous behavior, but now it shouldn't do that anymore, that's probably what's causing some of these problems. We should also somehow revert the UI changes if we were actually too optimistic and the operation didn't succeed (this is perhaps very rare when considering the current state, but in the future instead of writing to the disk directly we might have to do so through a network request).

> The note was still there but was completely empty, I guess that I just happened to close Notable right after creating the file.

 I've also seen an empty note getting read from the disk during development when I had set Notable to autosave every millisecond and I was writing very quickly, I'm not sure why that's happening actually, maybe Node.js is emptying the file before replacing it's content or something. 

Anyway we should definitely wait for any pending storage activities and API calls.

**Comment by mikaelmello** [comment]
Great, thanks for this response explaining everything (I think the term I'm look for is well-thought?).

All the best!

**Comment by fabiospampinato** [comment]
I'm calling this fixed as we are now:

- Renaming + overwriting notes instead of deleting + recreating them https://github.com/notable/notable/commit/4f03f7e896a7ea1a7bc136eaea409e8af4874fea

- Doing the renaming + overwriting more synchronously in order to avoid race conditions https://github.com/notable/notable/commit/83df1f43b4268ddbdca98031d2508ebef01bbdaa

- Waiting for any pending API or IO operations before actually closing the app https://github.com/notable/notable/commit/0cc5c0a1261dd212f5fcb94d76079a93a7c68028

Let me know if anybody can still reproduce this from the master branch/v1.4 👍

**Comment by mikaelmello** [comment]
Great! I'll test it later today
