### ISSUE TITLE
Add ability to zoom mermaid diagrams

### ISSUE THREAD

**Issue by hytromo** [notable/notable#485]
### Feature description

I would imagine every mermaid diagram to have 2 buttons to zoom in and zoom out. 

### Feature motivation

This is essential for bigger mermaid diagrams that are minuscule in my 15'' and even larger screens.

**Comment by fabiospampinato** [comment]
What about instead a button for opening the diagram in an external svg viewer (like a browser maybe)? 🤔

**Comment by CavalloneChen** [comment]
> What about instead a button for opening the diagram in an external svg viewer (like a browser maybe)? 🤔

This is a good solution. It's reasonable to keep notable relatively simple and clean.

**Comment by hytromo** [comment]
Yes opening in an external program sure is a viable solution!

**Comment by themetalfleece** [comment]
The browser solution would work, but how about zooming in/out the svg with a combination like ctrl-mouse wheel? So the Notable UI remains the same, but the wanted functionality is added.
I've found out that the zoom functionality is achieved by modifying the percentage of the `width` property of a svg (with the developer tools inside notable), so an event could be added to adjust it.

**Comment by fabiospampinato** [comment]
> how about zooming in/out the svg with a combination like ctrl-mouse wheel?

Sounds complicated. First of all the shortcut is a bit obscure so most people won't even know it exists, and for implementing this we would have to handle panning, zooming, zooming exactly from the cursor's position rather than just enlarging the diagram... Maybe we could implement this, but it requires some time, and there are more pressing features to implement first.

**Comment by fabiospampinato** [comment]
Here you have it:

![ezgif-5-a60b913007ec](https://user-images.githubusercontent.com/1812093/57186790-dadd1980-6ee5-11e9-8858-23fc37e65112.gif)

It turned out to be a weird thing to code, what I thought it would be the tricky part, getting the CSS and everything needed into a single svg file, turned out to be trivial since mermaid does already all this by default. The tricky part turned out to be simply **opening** the image:

- We could save the diagram as an `.svg` on the computer, but:
  - This is not future proof, as you can't do that from the future web-app #83 
  - Once you open it an unintended program might try to handle it: I had [Gapplin](http://gapplin.wolfrosch.com/) installed and it couldn't properly display the image, once uninstalled the image was being opened by [ImageOptim](https://imageoptim.com/mac). And that's just on my computer, other folks would have had similar issues.
  - We could tell the program to open Chrome specifically, but who knows what's the default browser on every system.
- We can convert the image into a "data:image/svg+xml..." url, but:
  - For some reasons we just can't open those urls from within the app.

The option I settled on is opening a separate window where the diagram can be displayed at full width. 

This isn't optimal though, what you actually want is to open the image in the browser. I think in order to do that I would have to setup a special-purpose website that tells the browser to display the image for you (something like `https://notable.md/displaythis#data:image/svg+xml...`), that'll have to wait until I get some time to work on the landing page #481.

For now I hope this would be good enough for most use cases, I'd be happy to hear your feedback on this.
