### ISSUE TITLE
View & Edit mode for text based attachments

### ISSUE THREAD

**Issue by Adrian-Grimm** [notable/notable#516]
### Feature description

It would be nice to be able to preview a textbased attachment.
Or like in Boostnote to be able to edit those files in a Split view.

### Feature motivation

Because as a programmer you often make smal short improvements on code snippets stored in such files or just to be able to copy a view lines...

**Comment by fabiospampinato** [comment]
🤔 Is it better in general to open the attachment with an external program? For instance if you're attaching a `.js` file or something I'd want that to be opened with my editor, which is tuned for editing those files, rather than having it opened in Notable, which is only really supposed to be editing Markdown files.

**Comment by Adrian-Grimm** [comment]
Maybe there should be an option to get a preview instead of opening those files - without editing possibilities. A view with syntaxhighlighting like prismjs.com and nothing else.

**Comment by fabiospampinato** [comment]
I'm not convinced about this use case, if you only want to preview the file just don't edit it. Maybe the problem here is that your editor starts up slowly or something? I'm not sure we should add another context menu action for this.

**Comment by Adrian-Grimm** [comment]
OK
