### ISSUE TITLE
Use natural sorting

### ISSUE THREAD

**Issue by OnyxDelta** [notable/notable#536]
### Feature description

Currently, this is the observed behavior:
![Image](https://user-images.githubusercontent.com/12561892/54142864-9ad24c80-43f6-11e9-89d9-1838b5437836.png)
It would seem to make more sense if numbers after 10 followed number 9, rather than following 1.
### Feature motivation

The current behavior makes it so that the list becomes unordered once notes that are numbered exceed 9 in their title.

**Comment by fabiospampinato** [comment]
I think the type of sorting you're proposing is called "natural sorting", it's probably a good idea to implement this 🤔

**Comment by baxtea** [comment]
I have a [branch](https://github.com/baxtea/notable/tree/natural-orderby) that correctly handles this case with [`natural-orderby`](https://www.npmjs.com/package/natural-orderby), but they currently have a bug that handles leading zeros incorrectly. Since that's how notable currently enforces proper ordering of numbers, it's quite glaring. I've filed an issue over there, will keep you posted.

**Comment by fabiospampinato** [comment]
Implemented in v1.6.
