### ISSUE TITLE
Preserve scroll position when a note's title changes

### ISSUE THREAD

**Issue by fabiospampinato** [notable/notable#539]
### Current behavior

1. Scroll the notes list
2. Update a note's title
3. As soon as the note is saved the list scrolls back to the top

### Expected behavior

The list should scroll in order to keep the currently active item visible.

**Comment by Armagedoom** [comment]
There are other areas in which the scroll position must be preserved:

* When folding / unfolding tags on the left pane, it goes back to top, so you have to scroll down in order to keep navigating your tab hierarchy. This is very disorienting and I found myself trying to avoid collapse / uncollapse tree because of this.

* When a markdown toggle box is marked, the MD file is reloaded and scrolls back to top of the document, so larger files with toggle box become very hard to deal with, the scroll should come back to its origin. What I mean by toggle box is:

- [ ] This.

* When changing between notes, the scroll is lost. If you open a note, scroll down, go to another, then open the first one again, the scroll will be back to top. This makes it very difficult to work with more than one note at the same time.

I am commenting here instead of creating a new issue because I think when fixing the scroll it will be easier to try and fix all the scrolling problems Notablewide, the code should be similar.

**Comment by fabiospampinato** [comment]
> The list should scroll in order to keep the currently active item visible.

I just fixed this, the fix will be available in the next release.

> When changing between notes, the scroll is lost. If you open a note, scroll down, go to another, then open the first one again, the scroll will be back to top. This makes it very difficult to work with more than one note at the same time.

@Armagedoom I don't remember if there's already an issue tracking this, if there isn't one feel free to open one.

**Comment by Armagedoom** [comment]
It is tracked [here](https://github.com/notable/notable/issues/339#issuecomment-459261434), but it just states "Active note scroll position". The definition here was more specific and included an example:

> When changing between notes, the scroll is lost. If you open a note, scroll down, go to another, then open the first one again, the scroll will be back to top. This makes it very difficult to work with more than one note at the same time.

**Comment by fabiospampinato** [comment]
I've updated the main post there mentioning "Previewing/editing state for all notes"
