### ISSUE TITLE
Quick open panel searches only on selected tag/Notebook

### ISSUE THREAD

**Issue by amelandri** [notable/notable#548]
- **OS Version**: Windows 10
- **Notable Version**: 1.4

### Current behavior

If I open the Quick Panel it shows a list of all notes but if I search for a note that's not in the currently selected tag/notebook, the note is not shown.

### Expected behavior

Since the quick panel shows all notes by default I expect that it searches in all notes.

**Comment by fabiospampinato** [comment]
Good catch, thanks!

**Comment by lmihalkovic** [comment]
This is one of the many ibvious problems that stem from the poor code organization.. I speak from knowledge, having studied it as closely over the last month as I did.

**Comment by fabiospampinato** [comment]
@lmihalkovic If you know of any other obvious or less obvious issues that haven't been already reported I'm all hears.

**Comment by amelandri** [comment]
> This is one of the many obvious problems that stem from the poor code organization.. I speak from knowledge, having studied it as closely over the last month as I did.

In my humble opinion, since you deeply studied the code, you should share your findings with Fabio and avoid posting harsh worthless comments.

**Comment by amelandri** [comment]
Sorry, I didn't mean to close the issue. My bad.

**Comment by lmihalkovic** [comment]
@amelandri , regarding your 

> In my humble opinion, since you deeply studied the code, you should share your findings with Fabio and avoid posting harsh worthless comments.

Maybe you could have an equally 'humble opinion' about the __harshness__ or __worthlessness__ of for calling Notable 'The markdown-based note-taking app that doesn't suck', in the face of so many basic bugs and poor code structure?  

we all look at things from our own personal viewpoints. I come from working on large systems, where we also have to care about design and architecture. from that standpoint, the code I am looking at is simply prone to problems (as proven by the simplicity of some of the many bugs reported).

As for making suggestions, I did point to some reading from very reputable people in the software industry who have described at length the issues I saw, and the response was ... lets just call it not enthusiastic.

**Comment by fabiospampinato** [comment]
Let me jump in on this: @lmihalkovic I'm also having the impression you're being a bit too harsh, without providing a proportional amount of actionable suggestions/bug reports/pull requests.

First of all you forked the app when it was licensed under the MIT license and apparently you don't want to share back all your changes, which is perfectly cool with me. But reading this on [your repo](https://github.com/lmihalkovic/notable#license):

> MIT © L. Mihalkovic, Portions Fabio Spampinato

Sounds a bit disrespectful to me for no good reasons. According to the commit history on that repo about 97% of the commits are mine, including the first one which contains about 1 month of my work. I mean yeah technically almost the totality of something is a _portion_ of that thing, but this just doesn't sound fair to me.

>  I did point to some reading from very reputable people in the software industry who have described at length the issues I saw, and the response was ... lets just call it not enthusiastic.

Just to provide some more context you're referring to [this discussion](https://github.com/notable/notable/commit/53fa36a7f733a246571e1d28c2101cf277f46f1b#commitcomment-32444504). 

There you mentioned that the codebase was better a week earlier, and in that week I actually mostly refactored a massive ~1k lines of CSS file into many modularized component, refactored the code in order to better support theming and made some general clean-up here and there.  I asked you what exactly did I made worse and you mentioned "leaky abstraction", suggested me some books to read and didn't provide any further pointer for my original question.

This feels like I'm receiving some judgment that says "just read the books" by a teacher of a school I never enrolled in. What did you expect me to do? Go read some books just because some bloke on the internet suggested me to do so?

> Maybe you could have an equally 'humble opinion' about the harshness or worthlessness of for calling Notable 'The markdown-based note-taking app that doesn't suck', in the face of so many basic bugs and poor code structure?

This sounds like when people instead of answering a question reply something like "Judge yourself before judging me". Instead it should probably have been better to start your comment with "My previous comment is not harsh or worthless because:".

I personally think that description is due for a change, it may currently sound like I'm shitting on other people's work as some people have pointed out. Which on some very obvious level is not entirely wrong, because if of all the note-taking apps I tried any of them was "the one" for me than I wouldn't have started my own. But I think it gets a bit misinterpreted as "all the other note-taking apps suck for everyone", while it should really be interpreted as "the minimum-viable (the "not sucking" part, it isn't great yet) note-taking app that I personally like".

> I come from working on large systems, where we also have to care about design and architecture. from that standpoint, the code I am looking at is simply prone to problems (as proven by the simplicity of some of the many bugs reported).

You mentioned this a few times already, and I'm not sure what that's supposed to mean, do you think people should just take your word as if it was law or something just because you're older than them or worked on some project? 

> This is one of the many obvious problems that stem from the poor code organization.. I speak from knowledge, having studied it as closely over the last month as I did.

Right, the code is poorly organized, but as I told you already I'm not able to make an app such as this ~perfectly in ~3 months. But I'm sure there are more knowledgable people than me that would have time a much better job than me in the same amount of time.

You mention there are "many obvious problems", what's that "many" supposed to mean? That our reported 190 issues are too many? That there are so many other unreported problems that for some reason you're not reporting? That those problems are so "obvious" because I'm incapable of writing good code?

In some sense that comment is kind of useless to me, as I'm getting nothing from it except some kind of non-constructive judgment.

In the future I'd appreciate more constructive comments here on the issue tracker. If what one's expressing is just an opinion/feeling/rant on something feel free to share it on the [subreddit](https://www.reddit.com/r/notable) instead, thanks.

**Comment by lmihalkovic** [comment]
Having shared publicly the negative opinion you have of the work of many others, implying that their work sucks solely because you do not like the features they chose to implement, or the manner in which they did so, I am quite surprised by the strength of your reaction. Especially considering how I refrained from using anything even remotely close for your work.

I do hope some people have the modicum of fairness required to recognize that, implying that the work of all these people who authored and shared their work sucks because they have a different view on what is essential could be construed as ... what is a word you might agree with? unfair? lacking elegance? harsh? self serving? un-necessarily denigrating?

Respect goes both ways, no?! and perhaps a more constructive approach might have been to demonstrate the quality of your work before being so judgemental of that of others.

**Comment by fabiospampinato** [comment]
>  implying that the work of all these people who authored and shared their work sucks because they have a different view on what is essential

Obviously if I want my notes to be written in Markdown it sucks if they are stored in XML, but the key part is "I", some other people may not care about this or may want features I'm not interested in, I'm not considering other note-taking apps as "not good" in general, but for me. If that weren't the case this repo wouldn't be here. 

And as I said I think this is not the right interpretation of the sentence, nor the one I intended:

>  But I think it gets a bit misinterpreted as "all the other note-taking apps suck for everyone", while it should really be interpreted as "the minimum-viable (the "not sucking" part, it isn't great yet) note-taking app that I personally like".

**Comment by lmihalkovic** [comment]
yes, on all accounts.. i expressed (and sill do) the personal opinion that the code was better before the large refactoring in question. I also added that in some ways, the code was also undeniably better (so that you would not consider that i was blind to some of the enhancements you made - the css coalescing being one of them).

Rather than drapping myself in the almightyness of my opinion, I referred you to the expert opinions of undisputed thought leaders in this industry, and proceeded to explained that I was doing it so that you would form your own opinion as well as to avoid you being tempted to make this something between you and me.

Lastly, I do APOLOGIZE for the copyright notice change that is a COMPLETE MISREPRESENTATION of the current situation. The description is indeed completely inapropriate for the code that is currently public!! I will clarify the situation.

**Comment by lmihalkovic** [comment]
I see, it is indeed a lot easier to just say that everything else sucks when one likes something else... How about testing that outside of the internet? we could both try independly and share thoughts about how wrong the others are if they fail to understand that we just prefer something else?! 

Can we test now?! Do I have your consent to call my fork ___the only fork that does not suck___ ?!? 😉

**Comment by fabiospampinato** [comment]
@lmihalkovic I'd advise against making the same mistake I made, but if it works for you you have my blessing ✌️
