### ISSUE TITLE
No more double-clicking to expand or collapse tags?

### ISSUE THREAD

**Issue by jlnbdt** [notable/notable#549]
Hi,
Thank you very much for this new version of Notable 😃 

I can no longer double-click to expand or collapse tags (I've to right click on them). Is it a bug or a normal behavior?

**Comment by fabiospampinato** [comment]
Hey, I've removed this because it was a bit confusing IMHO and now we have a button for collapsing tags:

![foo](https://user-images.githubusercontent.com/1812093/54445736-af3f7d80-4745-11e9-9cd5-5f321f0ee2db.gif)

Root tags such as "Notebooks" or "Tags" needs to be collapsed via a right click though. Perhaps I could add that clicking their icon collapses/expands them, but that might be confusing especially if in the future we add support for custom tag icons 🤔

**Comment by jlnbdt** [comment]
Ok, thanks for the explanation.
IMHO, it's very confusing to have two ways of managing tags collapsing, depending on their level. In addition, using right click is note very convenient.

Is it not possible to add the little button (the arrow) next to the root tag icons?

**Comment by fabiospampinato** [comment]
> IMHO, it's very confusing to have two ways of managing tags collapsing, depending on their level.

The right-click version is always available.

>  In addition, using right click is note very convenient.

Right, but I don't think collapsing those root tags is something that one does very often.

> Is it not possible to add the little button (the arrow) next to the root tag icons?

It's possible, we could add one of those arrows there too, but then those root collapsible tabs will no longer be aligned with the other non-collapsible root tags, I don't think it's worth it.

**Comment by xplatinum** [comment]
I never collapse notebooks because there's a handful of them. Tags grow much faster and it's not visually pleasing.
