### ISSUE TITLE
Middlebar Note title encoding HTML entities; not showing :emojis:

### ISSUE THREAD

**Issue by blakek** [notable/notable#563]
The middlebar is showing encoded HTML entities and not showing emojis using colon syntax.

**EXAMPLE**

![Screen Shot 2019-03-18 at 7 10 36 AM](https://user-images.githubusercontent.com/4932702/54529127-f5b2f900-494c-11e9-9d6b-ca3f3f73a5a3.png)

I'm assuming the first part could be resolved if the title text was set using `dangerouslySetInnerHTML` [here](https://github.com/notable/notable/blob/9817109d22d20a45532d10e08ddbd6216cbef12f/src/renderer/components/main/middlebar/note.tsx#L18).

(This may be two separate issues. Also, I tried to look and didn't see this reported yet; apologies if it's known)

- **OS Version**: macOS 10.14
- **Notable Version**: 1.4.0

### Current behavior

Create a new note with special characters and/or emojis using colons in the title.

### Expected behavior

Middlebar note title shows character instead of entity; shows emoji (preferable) or text for emojis.  For example: `# Handles :sparkles: & 🦄 &copy;` should show a note titled "Handles ✨ & 🦄 ©"

**Comment by fabiospampinato** [comment]
> The middlebar is showing encoded HTML entities

That's definitely a bug, I'll look into that.

> and not showing emojis using colon syntax.

This change was intentional, as treating titles as markdown had all sorts of issues, and rendering all those strings as Markdown seems also unwise performance-wise.

**Comment by patricksettle** [comment]
Side effect of the intentional change to not render markdown  (which is understandable)  in titles also causes titles and file names to ignore any text between two colons, even when not intended to be an emojis using colon syntax.

Examples:
`initial line in file -> Title in side bar -> file name`

(Original/Expected Behavior)
`# Key:ProjectX:Title  -> Key:ProjectX:Title -> Key ProjectX Title.md` 

(Current Behavior)
`# Key:ProjectX:Title  -> KeyTitle -> KeyTitle.md` 
`# Key:ProjectX :Title  -> Key:ProjectX :Title -> Key ProjectX Title.md`
`# Key: ProjectX:Title  -> Key: ProjectX:Title -> Key ProjectX Title.md`

Instead of not rendering the colon emoji text as markdown, it is omitting the text completely.

**Comment by fabiospampinato** [comment]
@patricksettle that's a problem 🤔 The solution isn't pretty but I think the app should check if the value between colons is actually a supported emoji 🤔

**Comment by patricksettle** [comment]
> > and not showing emojis using colon syntax.
> 
> This change was intentional, as treating titles as markdown had all sorts of issues, and rendering all those strings as Markdown seems also unwise performance-wise.

I thought by this the "intentional change" was that Notable would not show emojis using the colon syntax? If so then there doesn't seem to be a need to bother with checking the colons at all when setting the yaml title or file name, treating them like any other non-alphanumeric character. 

So if someone where to attempt to use a emoji in the first line of the text, the markdown view would parse `:joy:` accordingly and show 😂 , but pull the title from the plain text and only get and show `:joy:` then the only thing you need is to deal with any utf-8 supported emoji?

Have started digging into code yet, so don't know what your up against yet.

**Comment by fabiospampinato** [comment]
@patricksettle That's another option, but I think perhaps removing any markdown entirely from the title is a better option 🤔

**Comment by fabiospampinato** [comment]
@patricksettle your issue with titles containing emoji-like syntax has been fixed, now only actual supported emojis will get stripped away https://github.com/notable/notable/commit/d88605341c26f9a123b4c7374fe03ab9b6a19276

**Comment by fabiospampinato** [comment]
I've addressed this:

- [here](https://github.com/notable/notable/commit/a4387afa7263f53a95fb7949341a78ec79d21299): I think that rendering emojis is actually the best option here, in some sense the markdown gets stripped away, but I see no reason to throw the emojis away too.
- and [here](https://github.com/notable/notable/commit/a771003029ed4e9f2a7f73a19417c53a5ab6119f): now entities are decoded from titles (but only when inferring the title, existing titles will still be broken, you'll have to trigger a new infer manually (by changing the title temporarily), in the future maybe I'll add something for updating all titles automatically).
