### ISSUE TITLE
Focus and auto-select Untitled text on the new note

### ISSUE THREAD

**Issue by Armagedoom** [notable/notable#639]
- **OS Version**: Windows 10 (tried in several different computers with Windows 10)
- **Notable Version**: 1.4.0

### Current behavior

When a new note is created (Control+N) and the focus is in the middle pane (List of notes) the focus should go to the edit pane as per this fix https://github.com/notable/notable/issues/505 but it remains in the middle pane.

### Expected behavior

The focus should go to the editor of the just created note as defined in https://github.com/notable/notable/issues/505.

**Comment by fabiospampinato** [comment]
I think this is no longer an issue as of v1.6.

**Comment by emiola** [comment]
What I see is that the focus is correctly set in some common cases:

1. immediately after launching the app
2. if before creating the note the focus was already on the mainbar

Otherwise, if the focus before creating the note is on middlebar, the focus is not set. Same thing happens if the focus is on the sidebar after an intermediate passage through the middlebar.

**Comment by fabiospampinato** [comment]
@emiola are you switching from preview mode to edit more and see no cursor in the editor?

**Comment by emiola** [comment]
Fabio, no, not really. I see the cursor this way. In fact switching with the 'command+E' shortcut is my workaround for this little annoyance, because it restore the focus on the note title in all the cases there is no focus immediately after creation.

**Comment by fabiospampinato** [comment]
@emiola I'm not sure I'm understanding the problem you are having. Can you provide a short video or something that showcases the issue?

**Comment by emiola** [comment]
The problem is not new, it's the same of the issue we are writing on. I'm talking about the focus on the note title immediately after creating a note with [Command/Ctrl+N]. What I see is that the (final) focus is on the title, and one can just start to type, only in some (relevant, but not all) cases. It seems to depend on what's the (previous) focus before creating a new note.

Again, working cases:

1. immediately after launching the app, creating a new note shows the final focus as expected on the new note title
2. adding one more note while we are already editing a note (previous focus on the mainbar), the final focus is again fine, it's on the new note title as expected

Not working cases:

if before creating a new note, one clicks on the sidebar (previous focus on the tag list) or on the middlebar (previous focus on the note list), then the newly created note title has no focus and it's necessary to click on the mainbar to move the focus to the editor and start to type, which is rather annoying.

Hope this is clearer. I'm happy to chat in Italian, though ;-)

**Comment by fabiospampinato** [comment]
I think it's clear now, thanks.

I'm unable to reproduce it though, am I doing it right (you can't see clicks in the gif but I'm actually clicking)?

![Kapture 2019-07-12 at 17 44 12](https://user-images.githubusercontent.com/1812093/61140945-c06a8200-a4cc-11e9-8c2e-578d81e2ad51.gif)


What OS are you on? Are you on Notable v1.6.2?

**Comment by emiola** [comment]
To me it looks like you are trying to edit an existing note with Cmd+E, not to create a new one with Cmd+N, correct? If so, this is a different situation.

I'm on Mac with v1.6.2.

**Comment by fabiospampinato** [comment]
Right, sorry. I'm still unable to reproduce the issue though:

![Kapture 2019-07-13 at 17 01 46](https://user-images.githubusercontent.com/1812093/61173172-f58bd880-a58f-11e9-843c-2af8c124c293.gif)

**Comment by Armagedoom** [comment]
Im afraid this is still an issue in Windows 10 too.
I noticed in the gif you uploaded, you didn't click the note tittles before creating a new one. 
If I do that, the issue is not there neither, it only happens if you click a note tittle (under the search bar) and then click control+N.
When the focus is in the editor, it works properly (new note will have the focus still on the editor and the tittle will be selected) but if the focus was on a tittle (under the search bar, the middle pane) it will be selected but no cursor appears.
You can see this behavior in the following gif:


![notable_bug](https://user-images.githubusercontent.com/4046326/61180927-cec8b300-a61e-11e9-8cf2-b3cba830c9ba.gif)

**Comment by fabiospampinato** [comment]
Ok I think I can finally reproduce this, thanks everybody for the help!

**Comment by fabiospampinato** [comment]
The issue is probably that by clicking somewhere else you're actually switching the focus to another element, but in v1.6 when the preview is visible the focus is kind of "trapped" inside of it unless you're focusing to something more important like an input element, I should probably implement something like that for the editor as well.

**Comment by Armagedoom** [comment]
Yes, when we click in the middle pane, the focus goes there and stays there even after we create a new note (control + N).
What needs to happen IMO is that when the new note command is issued, the focus must go to the editor regardless of where it is currently, because after creating a new note the user will always want to name it (or so I think).
I don't see how implementing something like that for the editor would work, since the focus its outside the editor when creating those new notes. but maybe Im missing something. Thanks!

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.
