### ISSUE TITLE
Updater: mitigate update errors

### ISSUE THREAD

**Issue by fabiospampinato** [notable/notable#645]
### Feature description

If an update has been found but there's has been an issue updating the app I think we should:

- Tell the user to download the app manually.

- Perhaps open the release/download page automatically.

### Feature motivation

We should minimize the percentage of people that don't update the app, especially if they don't do it because the updater breaks.

**Comment by Trenar** [comment]
Hi Fabio,
for me, as I'm using the AppImage on Ubuntu, the auto-updater fails because it tries to download from the wrong link. 
The update process tries to download from 
`https://github.com/notable/notable/releases/download/v1.5.0/notable-1.5.0-x86_64.AppImage`, which gives me an error 404, because the correct link would be 
`https://github.com/notable/notable/releases/download/v1.5.0/Notable.1.5.0.AppImage`, without the `-x86_64` at the end.

You might want to fix the broken link.

Best,
Trenar

**Comment by fabiospampinato** [comment]
@Trenar yeah for some reason the builder isn't pointing to the right file. Let's track this here: #556
