### ISSUE TITLE
Tag tree should prevail as navigation tool

### ISSUE THREAD

**Issue by Armagedoom** [notable/notable#655]
### Feature description

Whenever the user edits a note, the currently selected navigation tag should prevail over the selected note configuration.

Explanation: This felt somewhat off ever since I started using Notable and now I am able to verbalize it.
Assuming the tags are the way we navigate between our notes, the fact that a note changes or looses the currently selected tag should move the user to the next available note in the same tag, it should not change the navigation for the user, because it is disorienting.
When you change a note and its gone, you can quickly guess that it is out of scope of your current navigation (same as it happens when you are filtering), but if you change a note and you are "teleported" to another tag its disorienting and get lost, more so if the currently selected tag is difficult to spot https://github.com/notable/notable/issues/638.
Moreover, if the note has several tags, the destination the user is "teleported to" is somewhat random (even if its the first tag of the note, the order of the tags is randomly assigned by the user, and cant be re-arranged so there is no control over that).
This is not a predictable behavior, thus the disorientation.

### Feature motivation

When the user is browsing your "Favourites" tags (or any other tag whatsoever), when he unmarks a tag, the UI should stay in the current tag and go to the next/first note available, instead of going to any random other tag that the note had, which turns out to be arbitrary.

**Comment by Armagedoom** [comment]
Just to add to it, when deleting a note, Notable behaves as described in this feature request, the Tag tree remains on its place.
I would expect the actions previously mentioned to behave consistently with the note deletion behavior.

**Comment by fabiospampinato** [comment]
I disagree with this (obviously since I implemented it this way). With your proposed solution if you want to remove a bunch of tags from a note you might need to constantly navigate around the app or retrieve that note from "All Notes", IMHO this shouldn't happen. You're editing a note, and that note should remain being edited.

> Just to add to it, when deleting a note, Notable behaves as described in this feature request, the Tag tree remains on its place.

That's the exception to the rule, the reasoning behind this is that if you deleted a note you're probably done with it and want to move on the next thing.

> the destination the user is "teleported to" is somewhat random 

There's no randomness, the behavior is specified here: https://github.com/notable/notable/blob/master/src%2Frenderer%2Fcontainers%2Fmain%2Ftag.ts/#L154-L186

> the order of the tags is randomly assigned by the use

It isn't tags are sorted alphabetically.
