### ISSUE TITLE
Automatic filenames contain emojis

### ISSUE THREAD

**Issue by jsosulski** [notable/notable#684]
- **OS Version**: Ubuntu 18.04
- **Notable Version**: 1.5.1

### Current behavior

Filenames contain emojis that are used in the title. While this looks quite interesting, especially in a terminal, it is rather hard to access files this way when they start with an emoji... :sweat_smile: 

![image](https://user-images.githubusercontent.com/2545339/59105044-5130c980-8933-11e9-9693-51e83ce2448a.png)

Furthermore, it seems dropbox is unable to sync files containing emojis in their path except the keyboard emoji.

![image](https://user-images.githubusercontent.com/2545339/59105214-c69c9a00-8933-11e9-8daf-82603f0160f9.png)

### Expected behavior

Emojis should be omitted from filenames if possible.

**Comment by fabiospampinato** [comment]
> Emojis should be omitted from filenames if possible.

IMHO the only characters that should be omitted from titles are disallowed characters under commonly used file systems (✅) and characters used for Markdown formatting (✅), since Markdown isn't rendered in titles/filenames.

Emoji fall under neither of those categories (we are actually rendering things like `:joy:` to the actual corresponding emoji for consistency though), so I don't think they should be removed.

> it is rather hard to access files this way when they start with an emoji... 😅

It will become easier once we have a CLI #667, but you can also fix that today by searching for your notes via something like [fzf](https://github.com/junegunn/fzf) (highly recommended).

> Furthermore, it seems dropbox is unable to sync files containing emojis in their path except the keyboard emoji.

This sounds weird to me, I don't see why they would make an exception for the keyboard emoji 🤨 Plus if they are unable to synchronize those kinds of files IMHO the problem is on their side.
