### ISSUE TITLE
Attachment Organization

### ISSUE THREAD

**Issue by ApolloBian** [notable/notable#747]
### Feature description

**Organize attachments in a note-wise space instead of a global space**. Have them renamed with a suffix generated from note name. Or organize them in a directory dedicated to each note. 

Also, **clicking the attachment in the attachment drop down menu copies the relative path** to the attachment instead of opening them in an external program will be much more convenient!.

### Feature motivation

Unlike notes, attachments can have the same name. However, the attachments are organized in a plain directory, just like notes. It is reasonable to organize them in one folder per note, or at least, rename them with an automatically generated  tags. 

For example, I can have a note that is about decorating and have an attachment named `window.png`, while in the same time another note about an algorithm that has a heatmap of a matrix, also named `window.png`:
<img src="https://user-images.githubusercontent.com/13659369/61423689-49f1d800-a943-11e9-8fc0-e08e9d33a2e9.png" height="200"><img src="https://user-images.githubusercontent.com/13659369/61423702-570ec700-a943-11e9-8275-522776cdc5dc.png" height="200">.

I can rename the attachment manually but as the number of notes goes up, it will be so troublesome to rename the attachment in an external fm.

**Comment by ApolloBian** [comment]
My current solution is to write a script monitoring the attachments folder, and it automatically renames any new attachments with a generated suffix, and print them in cmdline. This solution works fine for me, but it still requires me to open up a terminal, which takes up a lot of space in a small monitor while I just want to enjoy the full-screen writing experience, and manually copy the renamed filename. I see that how  to organize directory is discussed a lot, but most of them focus on how to organize notes instead of attachments.

**Comment by fabiospampinato** [comment]
> I see that how to organize directory is discussed a lot, but most of them focus on how to organize notes instead of attachments.

Yeah but let's keep the discussion into the [Improve file system structure](https://github.com/notable/notable/issues/54) issue, which is general enough to talk about attachments too.

> Also, clicking the attachment in the attachment drop down menu copies the relative path to the attachment instead of opening them in an external program will be much more convenient!.

I don't think that makes sense, clicking a note opens a note, clicking an attachment opens the attachment, clicking (or double-clicking) a file in your file explorer opens that file.

There's a context-menu action available for copying it instead.

I see pros to your proposal but also some downsides, like: should we duplicate attachments if we are linking to them multiple times? If attachments are named after the (first) note they are linked to, should we rename them every time that note is renamed?

Perhaps we should maintain some metadata for attachments too, so that multiple attachments can have the same name.
