### ISSUE TITLE
Change the reload shortcut

### ISSUE THREAD

**Issue by danielvelara** [notable/notable#757]
### Feature description

Change the reload shortcut from <kbd>cmd+r/ctrl+r</kbd> to <kbd>cmd+alt+r/ctrl+alt+r</kbd> (or something simliar)

### Feature motivation
I use Notable on a daily basis and I always use <kbd>cmd+e</kbd> for quickly previewing and editing, but sometimes I accidentally use <kbd>cmd+r</kbd> and it reload the application all the time and it very infuriating to have the app reload all the time.

**Comment by fabiospampinato** [comment]
The real solution to this would be to:

- Add a command for reloading the window to the command palette #338.
- Have support for customizable shortcuts #477, so that one could have the shortcuts he wanted.

Since none of those things are implemented yet I suppose your proposal to use `CmdOrCtrl+Alt+R` should be implemented.

Thanks for the suggestion 👍

**Comment by fabiospampinato** [comment]
It looks like we are using `CmdOrCtrl+Alt+R` already for revealing a note in its containing folder. `CmdOrCtrl+Shift+R` would probably have a similar root issue, and it will actually interfere with a shortcut I have enabled on development.

I've changed it to `F5` for now, if you can think of a better one I'm all ears.
