### ISSUE TITLE
32-bit version

### ISSUE THREAD

**Issue by Syenta** [notable/notable#76]
Hi,

Sorry for posting this here as it isn't an issue. I would have contacted you via Twitter but you haven't posted anything there since 25 Feb 2012.

I see you have a myriad, OK perhaps not ten thousand as such, of download options but not a 32-bit version. Is this something you will consider providing as there are still those of us out there who are using such hardware?

Many thanks

**Comment by fabiospampinato** [comment]
> Sorry for posting this here as it isn't an issue.

It's ok, it actually helps me keep track of everything to do :)

> I see you have a myriad, OK perhaps not ten thousand as such, of download options but not a 32-bit version. Is this something you will consider providing as there are still those of us out there who are using such hardware?

Is there any reason why you can't upgrade to a 64-bit OS? I'm not sure if I can add support for this, we are mostly just using [electron-builder](https://github.com/electron-userland/electron-builder) for building the app.

I'll keep this issue open to monitor how important this feature is also for other people, but I'd prefer not to add support for this even if only just for keeping the release page easier to use since as you mention there are already a myriad of download options.

**Comment by Syenta** [comment]
Thanks for getting back in touch.

"Is there any reason why you can't upgrade to a 64-bit OS" - Yes, the hardware can't handle 64-bit software as it has a 32-bit architecture.

The latest major bit of software I installed was a 32-bit version of Microsoft Office 2019. So if they are providing it there must be a large enough market to make it worth their time. I used this to show there is still a large enough market for 32-bit software, nothing else.

Anyway, I'll keep my fingers crossed that others will approach for a 32-bit version and I will watch from afar but not too far. ;-)

**Comment by fabiospampinato** [comment]
Thanks for the extra details. Let's keep this open so that other people can ":+1:" the issue.

**Comment by polinom11** [comment]
I wanted to switch to your application, but without the 32 bit version, the application is useless for me. I synchronize my notes between several devices, including on a working computer on which I cannot install a 64-bit operating system.

**Comment by ThomasLeigh** [comment]
> I'll keep this issue open to monitor how important this feature is also for other people

I can't upgrade My hardware now, so I stick with 32-bit ver. of everything because only those are working on My PC. I'd love to benefit out of markup and Notable - but without 32-bit ver. it isn't possible :( .

**Comment by yougotwill** [comment]
I'm in the same situation as @polinom11. My work computer is only 32-bit and I have to use a portable  apps due to admin restrictions. I really love notable and use it on my personal pc all the time. Having 32-bit would be the icing on the cake. Keep up the good work @fabiospampinato

**Comment by fabiospampinato** [comment]
It looks like 32-bit bundles of the app can be made pretty easily, and often both the 32-bit and 64-bit versions of the app are shipped within the same executable.

So there's a good chance that 32-bit bundles will be published in v1.8 (~early October).

What OS are you guys using? I think I've bot 32-bit bundles for Windows mostly figured out, do we need 32-bit bundles for other OSes too?

**Comment by rosemaryginfizz** [comment]
You are awesome! Thanks a lot for making the effort. I'm using ParrotOS, which is based in Debian Linux. The Debian package you provide works flawlessly on my workstation (64-bit Parrot), and it would be great to be able to use it on the laptop as well (32-bit Parrot because old) to have my notebooks available in both machines. So here's hoping that a 32-bit Debian package will be possible, too. 

Am Mo, 26. Aug 2019, um 21:02, schrieb Fabio Spampinato:

**Comment by fabiospampinato** [comment]
I'll see if I can make a 32-bit `.deb` too 👍 I read that there are issues when bundling for 32-bit versions of Linux for a 64-bit system though 🤔

**Comment by yougotwill** [comment]
@fabiospampinato I use Windows 7 32bit at work. I really appreciate you looking into this! Thanks and keep up the great work 😄

**Comment by rosemaryginfizz** [comment]
> I'll see if I can make a 32-bit `.deb` too :+1: I read that there are issues when bundling for 32-bit versions of Linux for a 64-bit system though :thinking:

I would gladly offer help if I could, but unfortunately my programming skills are below basic. Thanks for looking into it!

**Comment by fabiospampinato** [comment]
v1.8 should work on 32-bit versions of Windows.

I've opened a separated issue for Linux: https://github.com/notable/notable/issues/882
