### ISSUE TITLE
Paste with selected text doesn't work correcly

### ISSUE THREAD

**Issue by renanwillian** [notable/notable#777]
- **OS Version**: Linux Ubuntu 19.04
- **Notable Version**: 1.7.0

### Current behavior
In a note, select a text:
![image](https://user-images.githubusercontent.com/30376796/62946957-0e1e2700-bdb8-11e9-8bb8-c2b47c4ee77c.png)

Copy (Ctrl+C) and with the text selected paste (Ctrl+V):
![image](https://user-images.githubusercontent.com/30376796/62947006-25f5ab00-bdb8-11e9-9b2d-a845f2dec3fa.png)

The text will appear duplicated.

Another example, same selected text, but now pasting the string '123':
![image](https://user-images.githubusercontent.com/30376796/62947643-440fdb00-bdb9-11e9-9fe7-594d6be11e78.png)

### Expected behavior
Pasting content should replace any selected text.

**Comment by renanwillian** [comment]
Tested in 1.7.2

Another example:
![Peek 2019-08-13 11-24](https://user-images.githubusercontent.com/30376796/62949728-1d53a380-bdbd-11e9-9de7-820c80808d74.gif)

**Comment by maxhemby** [comment]
**OS Version:** Windows 10
**Notable Version:** 1.7.0

I also have this issue

**Comment by fabiospampinato** [comment]
I had to rewrite the logic for pasting because of the implementation of #26, it looks like I didn't handle everything correctly, it looks like we need a v1.7.3 release, thanks for reporting the issue 👍

**Comment by fabiospampinato** [comment]
The issue here is that we are not disabling pasting in the editor properly, we need to do that as we are handling pasting ourselves in order to also support attaching images via copy/paste.

Unfortunately [Monaco editor](https://github.com/microsoft/monaco-editor) is a total mess to work with, it feels like it hasn't been designed to be much more than VSCode's editor... This will take a bit, hopefully I won't have to resort to patching the editor.

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.

If you, poor soul reading this comment, have also stumbled about the issue of how to disable pasting in Monaco editor here's a solution that actually works:

```ts
import {CodeEditorWidget} from  'monaco-editor/esm/vs/editor/browser/widget/codeEditorWidget';

const _trigger = CodeEditorWidget.prototype.trigger;

CodeEditorWidget.prototype.trigger = function () {
  if ( arguments[1] === 'paste' ) return; // Disabling pasting
  return _trigger.apply ( this, arguments );
};
```

**Comment by gregunz** [comment]
I am on windows. 
I just downloaded and installed the latest release from github (1.7.3).

When pasting text or image, it pastes twice.

**Comment by gregunz** [comment]
Oh, in fact this is due to something else.

If you change the "Change Data Directory", it seems like there is sort of an instance of the editor which is still running, because after that it pastes twice.
If you change it again, it will paste three times, and so on.

Restarting the app solves it, but this might cause other issues as well and should be fixed.
