### ISSUE TITLE
Stop auto-opening Github release notes

### ISSUE THREAD

**Issue by logicbomb421** [notable/notable#801]
### Feature description
Currently when I open Notable and it needs an update, it opens the releases page in this repository. This is _very_ jarring when working, as it takes focus away from literally whatever you are doing to show you a webpage that will just be closed immediately. I've also had it open the notes at seemingly random times (e.g. opened Notable when I arrive at 8AM, release notes auto-open around noon when I switch back to the app).

### Feature motivation

This is driving me insane. At lease make this user-configurable please!

**Comment by fabiospampinato** [comment]
This sounds like a bug, it should only open the releases page when encountering an error while checking for updates, what OS are you on? Which file did you install Notable from?

**Comment by fabiospampinato** [comment]
I think the most common cause under which this happened was when the app had no internet connection, now the app always makes sure it has access to the internet before attempting to check for updates.

The reported behavior may still happen though if an error is encountered, and that's IMHO a good thing.

In the near future I'll start collecting these sorts of errors so that I can attempt at minimizing them.

I also thought about adding a button for opening the release page rather than just opening it automatically, but unfortunately for technical reasons this is not quite implementable cleanly so I'm not doing it for now.
