### ISSUE TITLE
Linking to files using file:/// does not work when directory or file has spaces

### ISSUE THREAD

**Issue by thansk** [notable/notable#812]
- **OS Version**: Ubuntu 19.04
- **Notable Version**: 1.7.3

### Current behavior

Linking to files using `file:///` works when the file and directory don't have spaces in their names, but does not work when they do have spaces. It just shows `[test](file:///home/user/Videos/Test Test/test.mp4)`. Escaping the spaces with `\` displays it as a link, but it does not open the video.

### Expected behavior

Working without the need of escaping spaces.

**Comment by fabiospampinato** [comment]
I think that's working as intended, if you're linking to files directly you'll have to provide a valid link to them, it works like this also for portability reasons, i.e. if you're not using Notable-specific features you should be able to write fairly standard Markdown.

The reason why that link is invalid is because, as you correctly pointed out, that links contains a space, so you have to escape it. You can escape spaces with a backslash in terminals, but for urls you have to url-encode it, basically you'll have to replace the space with "%20" (I think).

**Comment by thansk** [comment]
Confirming that using %20 works.
Thank you!
