### ISSUE TITLE
Will notable return to the open source?

### ISSUE THREAD

**Issue by davidhqu** [notable/notable#866]
#### Will Notable Return to the Open Source?

This is a great piece of software and I really enjoy using it. I appreciate the job that you are doing and how active you remain. But, I am curious...

**Comment by johnletey** [comment]
Please look at #432

**Comment by fabiospampinato** [comment]
@davidhqu Read the issue John linked you, the TL;DR is: I don't know, maybe, I'll reevaluate the current decision once the project becomes sustainable/profitable.

**Comment by ssbarnea** [comment]
Sad that is not possibille to flag repositories on github to want to avoid. I saw this kind of moves in the past, and they never went good (for both sides). Time to move on to a fully open-source app.

PS. There are working business models that do play well with open-souce.

**Comment by fabiospampinato** [comment]
> Sad that is not possibille to flag repositories on github to want to avoid

What would you need that for? Like what's the difference with just not visiting it?

> There are working business models that do play well with open-souce.

Maybe there are, as a solo developer working on this full-time I'd rather reduce as much risk as possible in that regard, like if I licensed the source under some open-source friendly license that doesn't mean somebody couldn't still just copy it and making a competing product out of it.

If anybody else would like the take the open-source route, starting from the available source code for v1.5.1 be my guest, I'd rather push for sustainability right now.

**Comment by ThinkTwiceCodeOnce-prog** [comment]
Firstly, let me thank you very much for your work on this feature-rich note-taking app, which - I totally agree with its community - has great potential in my eyes.
But - let me just quickly explain, why I cannot comprehend your decision to make this app closed-source. In the following, I just want to state my concerns - please do not think of it as a (personal) critique.
There are other great open-source applications on Github (not like the "big" ones e.g. Atom, Microsoft with VS Code etc.), who prove to be very innovative due to the fact, that everyone can contribute. In fact all can pull requests or building the app themselves, which accelerates the development of new features extremely. Anyway, the community's amazing response to your project (among other influences) goes back to exactly these possibilities of contribution.
In #432 you emphasized that you _"have more than a hundred open source projects too"_. Take it as an constructvely-meant advice if I guess, that it would be worthy to rather concentrate on a few - instead of having to be concerned about your valuable time (risking "stealing" by others) and therefore **preventing** a constant effort by the community by closing source in this awesome project. You are right there are these risks but it is what "open source" means on the other side (apart from being open): everyone can use it and hast the chance to improve it, kind of a competition which is natural among great project approaches.
