### ISSUE TITLE
Broken mermaid chart with dots ("...") after upgrade to 1.8.0

### ISSUE THREAD

**Issue by ribtoks** [notable/notable#886]
- **OS Version**: Windows 10
- **Notable Version**: 1.8.0

### Steps to reproduce

Add mermaid chart

    ```mermaid
    graph TD
      subgraph ...
      p2(...)
      end
    ```

### Current behavior

> [mermaid error: Failed to execute 'querySelectorAll' on 'Document': '#mermaid-fbfdc31f0b918cada8b034de407360d918e43f0a #... rect' is not a valid selector.]

### Expected behavior

Diagram is rendered

**Comment by fabiospampinato** [comment]
That's not a valid mermaid graph, it throws the same error in the official editor: https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgc3ViZ3JhcGggLi4uXG4gIHAyKC4uLilcbiAgZW5kIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifX0/error/RmFpbGVkIHRvIGV4ZWN1dGUgJ3F1ZXJ5U2VsZWN0b3JBbGwnIG9uICdEb2N1bWVudCc6ICcjbWVybWFpZC0xNTczMzIyMTE3Nzg5ICMuLi4gcmVjdCcgaXMgbm90IGEgdmFsaWQgc2VsZWN0b3Iu

The issue is somewhat related to those "..." parts, it looks like only things that can be CSS selectors are supported, this may be an issue about mermaid itself, maybe they should hash those strings or something.
