### ISSUE TITLE
Telemetry data

### ISSUE THREAD

**Issue by ForlornWongraven** [notable/notable#895]
What telemetry data is submitted to the project?
There should be a proper hint that telemetry is enabled by default since 1.8.0 and maybe an option to disable it on the GUI.

**Comment by fabiospampinato** [comment]
> What telemetry data is submitted to the project?

You can check this yourself via the "Network" tab in the devtools by inspect the requests made to Amplitude's server.

Today the app is reporting 2 events, `app:init` and `app:quit`, the last of which is implemented pretty naively, i.e. since the app is quitting most of the times the request isn't even made.

This is the object transmitted for me for the `app:init` event, with comments for each property:

```json
{
  "app_version": "1.8.1", // Notable's version
  "platform": "darwin 10.14.6", // Current OS
  "user_id": "54b23678141a551ea6551838fefc6f374dc78f18", // Unique random identifier, needed for understanding if the app has been opened 5 times by 5 different people or just open person is opening and closing it multiple times. It may also be useful for clustering future events together, probably some useful patterns may emerge from that.
  "ip": "90.220.207.0", // Anonymized IP, the last portion is zeroed
  "time": 1573518451036, // Timestamp of the event
  "event_type": "app:init", // Event name
  "event_properties": {} // Additional event data
}
```

I'll add a setting to turn this off, even though I don't think there's any good reason why one should do it, once we'll have proper settings #476.

**Comment by fabiospampinato** [comment]
> There should be a proper hint that telemetry is enabled by default

You mean like an icon somewhere or something? That could only be useful for the people that for some reason what to turn this off, and would clutter the UI. I could add a popup at startup or something about this, but since I don't think I need to ask for confirmation for collecting these sorts of data (I'm not collecting any PII as far as I can see) I'd rather not show at confirmation wall at startup.

**Comment by ForlornWongraven** [comment]
Good point. Maybe add something to the tutorial when the app is launched for the first time. Transparency is always a good thing and when this only "costs" one or two lines in the tutorial it's well worth it.

**Comment by kinghat** [comment]
> i would disclose all data collected, anonymized or not, everywhere. also, provide options to disable it on initial install and after the fact.

referenced here: https://www.reddit.com/r/Notable/comments/e2pqmh/notable_v182/f93jkh3
