### ISSUE TITLE
Math (katex) won't render if it starts with open angular bracket 

### ISSUE THREAD

**Issue by JayZ2398** [notable/notable#918]
- **OS Version**: Ubuntu 18.04.3 LTS
- **Notable Version**: 1.8.1

### Current behavior

Create inline or display math starting with a < character.

```
$<$
$3<$
$</3$
$>$
```

Get this:
![image](https://user-images.githubusercontent.com/28042291/69116354-336db000-0ae0-11ea-9fd8-f93916c127ca.png)

`3<` and `>` render fine.

### Expected behavior

Math renders correctly.

**Comment by fabiospampinato** [comment]
I just "fixed" this, the fix will be available in the next release. The thing is I was using the presence of the "<" character has an indication that the following wasn't actually a KaTeX expression but some HTML, I've improved the regex to better avoid false positives, but this isn't a "proper" solution, there will always be cases were our regexes are matching something incorrect because this problem is not solvable by regexes, I'll have to figure out how to write more reliable markdown extensions in the future.

**Comment by JayZ2398** [comment]
That’s all good - Latex would probably recommend ‘\lt’ or ‘\langle’ anyway.

Thanks for the speedy responses and fixes as always!
