### ISSUE TITLE
Move `~/.notable.json` to `~/Library/Application Support/Notable`

### ISSUE THREAD

**Issue by JeffersonBledsoe** [notable/notable#936]
It would be nice to not have Notable add files to my home directory. While I know it's a hidden file and alot of people won't see it, as a developer I usually show most hidden files.

There is already a config file in the app support folder, `notable.json`, is there a particular reason the two couldn't be merged?

**Comment by fabiospampinato** [comment]
- `~/.notable.json` is used by the current settings library I'm using.
- `~/Library/Application Support/Notable/notable.json` is used by the library I'm using for remembering the window position, so that it can be restored properly.

The two files can be merged into one, and I'll probably do that once I'll switch to a better settings library (https://github.com/fabiospampinato/configuration), but I don't want to move all settings to `~/Library/Application Support/Notable`, I'll probably move them to `~/.notable` or `~/config/.notable`, which is just more convenient to reach if you need to.
