### ISSUE TITLE
[PDF] - page breaks & one-file pdf export

### ISSUE THREAD

**Issue by DanteDeRuwe** [notable/notable#971]
#### Page breaks 📄 
When typing notes I should be able to:
* **visually** see page breaks in the preview
    * if preferred --> togglable in settings?
* insert page breaks in the editor
    * **custom command** would be handy, `<pagebreak>`?

I've been using `<div style="page-break-after: always;"></div>`, but this is ugly and I can only see how the layout will be when I export to pdf. My workflow to export to pdf consists of multiple re-exports just to get the page layout right. (*)

#### One-file pdf exporting ~~:file_folder:~~
PDF's now export into a **folder**, containing the PDF itself and an attachment folder. This in my opinion is not necessary, as pdf is perfectly **portable** as standalone file (html and md both require a seperate "attachments" folder; pdf does not). 

### Feature motivation
Mostly I type notes with the intent of printing them, or storing them on my HDD as pdf's, so they are completely portable. I want my pages to be seperated correctly, so page breaks are essential. 
One-file exports would be a blessing as well; always having to cut the pdf out of the folder into a new location and then delete the folder, in combination with (*), is very frustrating.

**Comment by fabiospampinato** [comment]
- Simple page break insertion: let's track this here: https://github.com/notable/notable/issues/972.
- No-folder exports: I'm not sure this is always a good idea, I can see the frustration arising for your use case, but if one's exporting 100 pdfs instead, especially if they contain non-embedded-in attachments, I'd expect them to be exported into a more manageable folder structure like the one we are using. Perhaps if one's exporting just one note, and that note doesn't have any attachments, we could just export that single PDF not wrapped into a folder? I'd work a little weirdly though IMHO, maybe just smoothing out your workflow would be better.
- Exporting just for checking page breaks: I think this would be resolved if I add a command for printing directly (#454), so that you can see a preview of the exported documented from there directly, and if you like it you can export it to PDF from there. The benefits would be: a faster way to check page breaks, no files to remove in case the page breaks don't look perfect, no wrapping folder as you'll be able to save the PDF from there directly. Would this mostly solve your issues?

**Comment by DanteDeRuwe** [comment]
Your approach does seem like the right solution. Haven't thought of multiple notes exporting at once. 

With the opening of the seperate page break issue, I'm closing this one.
